## Name :- clavin dsouza
## Roll No :- 20
## Batch :- 1
## ML Lab Exp 5

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
import pandas as pd
import numpy as np

In [ ]:
data = load_breast_cancer()

x = data.data
y = data.target

print("Classes: ", data.target_names)

Classes:  ['malignant' 'benign']

In [ ]:
df = pd.DataFrame(x)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       569 non-null    float64
 1   1       569 non-null    float64
 2   2       569 non-null    float64
 3   3       569 non-null    float64
 4   4       569 non-null    float64
 5   5       569 non-null    float64
 6   6       569 non-null    float64
 7   7       569 non-null    float64
 8   8       569 non-null    float64
 9   9       569 non-null    float64
 10  10      569 non-null    float64
 11  11      569 non-null    float64
 12  12      569 non-null    float64
 13  13      569 non-null    float64
 14  14      569 non-null    float64
 15  15      569 non-null    float64
 16  16      569 non-null    float64
 17  17      569 non-null    float64
 18  18      569 non-null    float64
 19  19      569 non-null    float64
 20  20      569 non-null    float64
 21  21      569 non-null    float64
 22  22      569 non-null    float64
 23  23      569 non-null    float64
 24  24      569 non-null    float64
 25  25      569 non-null    float64
 26  26      569 non-null    float64
 27  27      569 non-null    float64
 28  28      569 non-null    float64
 29  29      569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [ ]:
df.shape

(569, 30)

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [ ]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
lr = LogisticRegression(max_iter=5000)

lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

print("Logistic Test Accuracy:", accuracy_score(y_test, pred_lr))

pred_lr_train = lr.predict(X_train)

print("Logistic Train Accuracy:", accuracy_score(y_train, pred_lr_train))

Logistic Test Accuracy: 0.9590643274853801
Logistic Train Accuracy: 0.9623115577889447

In [ ]:
dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

pred_dt = dt.predict(X_test)

print("DecisionTree Test Accuracy:", accuracy_score(y_test, pred_dt))

pred_dt_train = dt.predict(X_train)

print("DecisionTree Train Accuracy:", accuracy_score(y_train, pred_dt_train))

DecisionTree Test Accuracy: 0.9122807017543859
DecisionTree Train Accuracy: 1.0

In [ ]:
knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

pred_knn = knn.predict(X_test)

print(" KNeighbors Test Accuracy:", accuracy_score(y_test, pred_knn))

pred_knn_train = knn.predict(X_train)

print(" KNeighbors Train Accuracy:", accuracy_score(y_train, pred_knn_train))

 KNeighbors Test Accuracy: 0.935672514619883
 KNeighbors Train Accuracy: 0.9396984924623115

In [ ]:
gnb = GaussianNB()

gnb.fit(X_train, y_train)

pred_gnb = gnb.predict(X_test)

print(" GaussianNB Test Accuracy:", accuracy_score(y_test, pred_gnb))

pred_gnb_train = gnb.predict(X_train)

print(" GaussianNB Train Accuracy:", accuracy_score(y_train, pred_gnb_train))

 GaussianNB Test Accuracy: 0.9239766081871345
 GaussianNB Train Accuracy: 0.9422110552763819

In [ ]:
mlp = MLPClassifier()

mlp.fit(X_train, y_train)

pred_mlp = mlp.predict(X_test)

print(" MLPClassifier Test Accuracy:", accuracy_score(y_test, pred_mlp))

pred_mlp_train = mlp.predict(X_train)

print(" MLPClassifier Train Accuracy:", accuracy_score(y_train, pred_mlp_train))

 MLPClassifier Test Accuracy: 0.9122807017543859
 MLPClassifier Train Accuracy: 0.9396984924623115

In [ ]:
cm_lr = confusion_matrix(y_test, pred_lr)
print("\nLinear Regression Confusion Matrix")
print(cm_lr)
TN1, FP1, FN1, TP1 = cm_lr.ravel()

type1_lr = FP1 / (FP1 + TN1) 
type2_lr = FN1 / (FN1 + TP1) 

print("FP (Type-I): ",FP1)
print("FN (Type-II): ",FN1)
print("Type-I error rate in %:", type1_lr*100)
print("Type-II error rate in %:", type2_lr*100)

Linear Regression Confusion Matrix
[[ 62   4]
 [  3 102]]
FP (Type-I):  4
FN (Type-II):  3
Type-I error rate in %: 6.0606060606060606
Type-II error rate in %: 2.857142857142857

In [ ]:
cm_dt = confusion_matrix(y_test, pred_dt)

print("\nDecision Tree Confusion Matrix:")
print(cm_dt)

TN2, FP2, FN2, TP2 = cm_dt.ravel()

type1_dt = FP2 / (FP2 + TN2)
type2_dt = FN2 / (FN2 + TP2)

print("FP (Type-I):", FP2)
print("FN (Type-II):", FN2)
print("Type-I Error Rate in %:", type1_dt * 100)
print("Type-II Error Rate in %:", type2_dt * 100)

Decision Tree Confusion Matrix:
[[63  3]
 [12 93]]
FP (Type-I): 3
FN (Type-II): 12
Type-I Error Rate in %: 4.545454545454546
Type-II Error Rate in %: 11.428571428571429

In [ ]:
cm_knn = confusion_matrix(y_test, pred_knn)
print("\nKNN Confusion Matrix")
print(cm_knn)
TN3, FP3, FN3, TP3 = cm_knn.ravel()

type1_knn = FP3 / (FP3 + TN3) 
type2_knn = FN3 / (FN3 + TP3) 

print("FP (Type-I): ",FP3)
print("FN (Type-II): ",FN3)
print("Type-I error rate in %:", type1_knn*100)
print("Type-II error rate in %:", type2_knn*100)

KNN Confusion Matrix
[[62  4]
 [ 7 98]]
FP (Type-I):  4
FN (Type-II):  7
Type-I error rate in %: 6.0606060606060606
Type-II error rate in %: 6.666666666666667

In [ ]:
cm_nb = confusion_matrix(y_test, pred_gnb)
print("\nNaive Bayes Confusion Matrix")
print(cm_nb)
TN4, FP4, FN4, TP4 = cm_nb.ravel()

type1_nb = FP4 / (FP4 + TN4) # False positive rate
type2_nb = FN4 / (FN4 + TP4) # False negative rate

print("FP (Type-I): ",FP4)
print("FN (Type-II): ",FN4)
print("Type-I error rate in %:", type1_nb*100)
print("Type-II error rate in %:", type2_nb*100)

Naive Bayes Confusion Matrix
[[ 57   9]
 [  4 101]]
FP (Type-I):  9
FN (Type-II):  4
Type-I error rate in %: 13.636363636363635
Type-II error rate in %: 3.8095238095238098

In [ ]:
cm_mlp = confusion_matrix(y_test, pred_mlp)
print("\nNeural Network Confusion Matrix")
print(cm_mlp)
TN5, FP5, FN5, TP5 = cm_mlp.ravel()

type1_mlp = FP5 / (FP5 + TN5) # False positive rate
type2_mlp = FN5 / (FN5 + TP5) # False negative rate

print("FP (Type-I): ",FP5)
print("FN (Type-II): ",FN5)
print("Type-I error rate in %:", type1_mlp*100)
print("Type-II error rate in %:", type2_mlp*100)

Neural Network Confusion Matrix
[[61  5]
 [10 95]]
FP (Type-I):  5
FN (Type-II):  10
Type-I error rate in %: 7.575757575757576
Type-II error rate in %: 9.523809523809524

In [ ]:
precision = precision_score(y_test, pred_lr)
recall = recall_score(y_test, pred_lr)
f1 = f1_score(y_test, pred_lr)
roc = roc_auc_score(y_test, pred_lr)

print("precision:", precision)
print("recall:", recall)
print("f1:", f1)
print("roc:", roc)

precision: 0.9622641509433962
recall: 0.9714285714285714
f1: 0.966824644549763
roc: 0.9554112554112556

In [ ]:
precision = precision_score(y_test, pred_knn)
recall = recall_score(y_test, pred_knn)
f1 = f1_score(y_test, pred_knn)
roc = roc_auc_score(y_test, pred_knn)

print("precision:", precision)
print("recall:", recall)
print("f1:", f1)
print("roc:", roc)

precision: 0.9607843137254902
recall: 0.9333333333333333
f1: 0.9468599033816425
roc: 0.9363636363636364

In [ ]:
precision = precision_score(y_test, pred_gnb)
recall = recall_score(y_test, pred_gnb)
f1 = f1_score(y_test, pred_gnb)
roc = roc_auc_score(y_test, pred_gnb)

print("precision:", precision)
print("recall:", recall)
print("f1:", f1)
print("roc:", roc)

precision: 0.9181818181818182
recall: 0.9619047619047619
f1: 0.9395348837209302
roc: 0.9127705627705629

In [ ]:
precision = precision_score(y_test, pred_mlp)
recall = recall_score(y_test, pred_mlp)
f1 = f1_score(y_test, pred_mlp)
roc = roc_auc_score(y_test, pred_mlp)

print("precision:", precision)
print("recall:", recall)
print("f1:", f1)
print("roc:", roc)

precision: 0.95
recall: 0.9047619047619048
f1: 0.926829268292683
roc: 0.9145021645021644